# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sarvagya Porwal
user_description: AI Engineer
user_title: AI Engineer
email: sarvp2486@gmail.com
twitter_username: x.com/sarp0424
github_username:  github.com/Sar2580P
gplus_username:  sarvp2486@gmail.com

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
